# Generated by Django 5.1.6 on 2025-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="is_partner",
        ),
        migrations.AddField(
            model_name="entity",
            name="is_partner",
            field=models.BooleanField(default=False),
        ),
    ]
