# Generated by Django 5.1.6 on 2025-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="backer_name",
        ),
        migrations.AddField(
            model_name="infrastructuredetails",
            name="legal_entity_description",
            field=models.TextField(null=True),
        ),
    ]
