# Generated by Django 5.1.6 on 2025-04-10 12:10

import tsosi.models.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0002_remove_infrastructuredetails_backer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="icon",
            field=models.ImageField(
                max_length=256,
                null=True,
                upload_to=tsosi.models.entity.entity_icon_path,
            ),
        ),
    ]
