# Generated by Django 5.1.6 on 2025-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0002_analytic"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="manual_logo",
            field=models.BooleanField(default=False),
        ),
    ]
