# Generated by Django 5.1.6 on 2025-04-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0003_entity_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="short_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
