# Generated by Django 5.1.6 on 2025-04-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0004_entity_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("http_status", models.IntegerField(null=True)),
                ("error", models.BooleanField(default=False)),
                ("error_msg", models.TextField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("wikipedia_extract", "Wikipedia extract"),
                            ("wikimedia_logo", "Wikimedia logo"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="tsosi.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("error", False), ("error_msg__isnull", True)),
                            models.Q(("error", True), ("error_msg__isnull", False)),
                            _connector="OR",
                        ),
                        name="tsosi_entityrequest_request_error_msg_when_failed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("type__in", ["wikipedia_extract", "wikimedia_logo"])
                        ),
                        name="valid_entity_request_type_choice",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentifierRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("http_status", models.IntegerField(null=True)),
                ("error", models.BooleanField(default=False)),
                ("error_msg", models.TextField(null=True)),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="tsosi.identifier",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("error", False), ("error_msg__isnull", True)),
                            models.Q(("error", True), ("error_msg__isnull", False)),
                            _connector="OR",
                        ),
                        name="tsosi_identifierrequest_request_error_msg_when_failed",
                    )
                ],
            },
        ),
    ]
