# Generated by Django 5.1.6 on 2025-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0005_entityrequest_identifierrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="identifierversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_end__isnull", True)),
                fields=("identifier",),
                name="unique_identifier_version_with_no_date_end",
            ),
        ),
    ]
