# Generated by Django 5.1.6 on 2025-05-06 08:43

import tsosi.models.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0006_identifierversion_unique_identifier_version_with_no_date_end"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transfer",
            name="transfer_at_least_one_date",
        ),
        migrations.RenameField(
            model_name="transfer",
            old_name="date_payment",
            new_name="date_payment_recipient",
        ),
        migrations.AddField(
            model_name="transfer",
            name="date_payment_emitter",
            field=tsosi.models.date.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_invoice__isnull", False),
                    ("date_payment_recipient__isnull", False),
                    ("date_payment_emitter__isnull", False),
                    ("date_start__isnull", False),
                    _connector="OR",
                ),
                name="transfer_at_least_one_date",
            ),
        ),
    ]
