# Generated by Django 5.1.6 on 2025-07-03 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0007_remove_transfer_transfer_at_least_one_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registry",
            name="record_regex",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="EntityName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("label", "label"),
                            ("alias", "alias"),
                            ("acronym", "acronym"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                ("lang", models.CharField(max_length=2, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsosi.entity",
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_names",
                        to="tsosi.registry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
