# Generated by Django 5.1.6 on 2025-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0008_registry_record_regex_entityname"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="raw_logo_url",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
