# Generated by Django 5.1.6 on 2025-07-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0009_entity_raw_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="scoss",
            field=models.BooleanField(default=False),
        ),
    ]
