# Generated by Django 5.1.6 on 2025-12-15 09:45

import django.db.models.deletion
from django.db import migrations, models


def make_many_data_load_sources(apps, schema_editor):
    """
    Adds the data_load_source object in Transfer.data_load_source to the
    many-to-many relationship in Transfer.data_load_sources
    """
    Transfer = apps.get_model("tsosi", "Transfer")

    for transfer in Transfer.objects.all():
        transfer.data_load_sources.add(transfer.data_load_source)


def make_json_raw_data(apps, schema_editor):
    """
    Adds the data_load_source object in Transfer.data_load_source to the
    many-to-many relationship in Transfer.data_load_sources
    """
    Transfer = apps.get_model("tsosi", "Transfer")

    for transfer in Transfer.objects.prefetch_related("data_load_source").all():
        transfer.raw_data = {
            transfer.data_load_source.data_load_name: transfer.raw_data
        }
        transfer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0010_transfer_scoss"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="merged_into",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_transfers",
                to="tsosi.transfer",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="data_load_sources",
            field=models.ManyToManyField(to="tsosi.dataloadsource"),
        ),
        migrations.RunPython(make_many_data_load_sources),
        migrations.RunPython(make_json_raw_data),
        migrations.RemoveField(
            model_name="transfer",
            name="data_load_source",
        ),
    ]
