# Generated by Django 5.1.6 on 2026-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tsosi",
            "0011_transfer_merged_criteria_transfer_merged_into_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="parents",
            field=models.ManyToManyField(
                related_name="children", to="tsosi.entity"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="types",
            field=models.JSONField(null=True),
        ),
    ]
