# Generated by Django 5.1.6 on 2026-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0012_entity_parents_entity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferentitymatching",
            name="sub_entity",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
