# Generated by Django 5.1.6 on 2026-01-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0013_transferentitymatching_sub_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataloadsource",
            name="entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tsosi.entity",
            ),
        ),
    ]
