# Generated by Django 5.1.6 on 2026-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0014_dataloadsource_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="date_data_end",
        ),
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="date_data_start",
        ),
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="date_data_update",
        ),
    ]
