# Generated by Django 5.1.6 on 2026-03-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0015_remove_infrastructuredetails_date_data_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="emitter_sub",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name="TransferEntityMatching",
        ),
    ]
