# Generated by Django 5.1.6 on 2026-03-04 09:49

from django.db import migrations, models


def migrate_agent_to_many(apps, schema_editor):
    Transfer = apps.get_model("tsosi", "Transfer")
    for transfer in Transfer.objects.all():
        if transfer.agent:
            transfer.agents.add(transfer.agent)


def migrate_agent_to_one(apps, schema_editor):
    Transfer = apps.get_model("tsosi", "Transfer")
    for transfer in Transfer.objects.all():
        if transfer.agents.count() > 0:
            transfer.agent = transfer.agents.first()


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0016_transfer_emitter_sub_delete_transferentitymatching"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="agents",
            field=models.ManyToManyField(
                related_name="transfer_as_agents",
                related_query_name="transfer_as_agent",
                to="tsosi.entity",
            ),
        ),
        migrations.RunPython(
            migrate_agent_to_many, reverse_code=migrate_agent_to_one
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="agent",
        ),
    ]
