# Generated by Django 5.1.6 on 2026-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0017_remove_transfer_agent_transfer_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="is_future",
            field=models.BooleanField(default=False),
        ),
    ]
