# Generated by Django 6.0.3 on 2026-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0018_transfer_is_future"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="types",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="data_load_sources",
            field=models.ManyToManyField(
                related_name="transfers", to="tsosi.dataloadsource"
            ),
        ),
    ]
