# Generated by Django 6.0.3 on 2026-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0019_alter_entity_types_alter_transfer_data_load_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_barcelona",
            field=models.BooleanField(default=False),
        ),
    ]
