# Generated by Django 5.1.6 on 2026-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0020_entity_is_barcelona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="types",
            field=models.JSONField(null=True),
        ),
    ]
