# Generated by Django 5.1.6 on 2026-05-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0021_alter_entity_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infrastructuredetails",
            old_name="legal_entity_description",
            new_name="legal_entity_wikidata_id",
        ),
    ]
