# Generated by Django 6.0.3 on 2026-05-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tsosi",
            "0022_rename_legal_entity_description_infrastructuredetails_legal_entity_wikidata_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructuredetails",
            name="hide_amount",
        ),
    ]
