# Generated by Django 6.0.3 on 2026-05-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0023_remove_infrastructuredetails_hide_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="transfer",
            name="support_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tsosi.supporttype",
            ),
        ),
    ]
