# Generated by Django 6.0.5 on 2026-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0024_supporttype_transfer_support_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="types",
            new_name="ror_types",
        ),
        migrations.AddField(
            model_name="entity",
            name="tsosi_type",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
