# Generated by Django 6.0.5 on 2026-08-18 09:31

import django.db.models.deletion
from django.db import migrations, models


def delete_identifiers_without_entity(apps, schema_editor):
    Identifier = apps.get_model("tsosi", "Identifier")
    Identifier.objects.filter(entity__isnull=True).delete()


def noop_reverse(apps, schema_editor):
    pass


def flatten_merged_transfers(apps, schema_editor):
    from tsosi.data.ingestion.transfer_matching import merge_transfers
    from tsosi.models import Transfer

    transfers = Transfer.objects.filter(merged_into_id__isnull=False).exclude(
        merged_transfers=None
    )
    for transfer in transfers:
        other_transfer = transfer.merged_into.merged_transfers.exclude(
            id=transfer.id
        ).first()
        transfer.merged_into.delete()
        merge_transfers(other_transfer, transfer)


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0025_rename_types_entity_ror_types_entity_tsosi_type"),
    ]

    atomic = False

    operations = [
        migrations.RemoveConstraint(
            model_name="identifier",
            name="unique_identifier_per_registry_and_entity",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="is_matchable",
        ),
        migrations.RunPython(
            delete_identifiers_without_entity,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name="identifier",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="tsosi.entity",
            ),
        ),
        migrations.RunPython(
            flatten_merged_transfers,
            reverse_code=noop_reverse,
        ),
    ]
