# Generated by Django 6.0.5 on 2026-08-31 12:08

from django.db import migrations, models
from django.db.models import Q


def set_entity_hide_amount(apps, schema_editor):
    """
    Flag a partner entity's `hide_amount` as True if it has at least one
    transfer (merged or not, as emitter/recipient/agent) that is sourced
    exclusively from its own data load source(s) and has `hide_amount=True`.
    """
    Entity = apps.get_model("tsosi", "Entity")
    DataLoadSource = apps.get_model("tsosi", "DataLoadSource")
    Transfer = apps.get_model("tsosi", "Transfer")

    entity_ids_with_source = set(
        DataLoadSource.objects.exclude(entity_id__isnull=True).values_list(
            "entity_id", flat=True
        )
    )

    entities_to_hide = set()
    for entity_id in entity_ids_with_source:
        transfers = Transfer.objects.filter(
            Q(emitter_id=entity_id)
            | Q(recipient_id=entity_id)
            | Q(agents__id=entity_id)
        ).distinct()
        for transfer in transfers:
            if not transfer.hide_amount:
                continue
            source_entity_ids = set(
                transfer.data_load_sources.values_list("entity_id", flat=True)
            )
            if source_entity_ids == {entity_id}:
                entities_to_hide.add(entity_id)
                break

    if entities_to_hide:
        Entity.objects.filter(id__in=entities_to_hide).update(hide_amount=True)


class Migration(migrations.Migration):

    dependencies = [
        (
            "tsosi",
            "0026_remove_identifier_unique_identifier_per_registry_and_entity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="hide_amount",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_entity_hide_amount, migrations.RunPython.noop
        ),
    ]
