# Generated by Django 6.0.5 on 2026-09-30 17:51

from django.db import migrations
from django.db.models import F, Q


def keep_raw_logos(apps, schema_editor):
    """
    `raw_logo_url` was the fallback logo URL for entities with no logo in
    their Wikidata record. Keep the logos fetched from it as manual logos,
    so that they're neither deleted nor refreshed by the logo update.
    """
    Entity = apps.get_model("tsosi", "Entity")
    Entity.objects.filter(
        raw_logo_url__isnull=False, logo_url=F("raw_logo_url")
    ).exclude(Q(logo__isnull=True) | Q(logo="")).update(manual_logo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0027_entity_hide_amount"),
    ]

    operations = [
        migrations.RunPython(keep_raw_logos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="entity",
            name="raw_logo_url",
        ),
    ]
