# Generated by Django 6.0.5 on 2026-09-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsosi", "0028_remove_entity_raw_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityEditAccess",
            fields=[
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=256, null=True)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("date_expires", models.DateTimeField()),
                ("date_revoked", models.DateTimeField(null=True)),
                ("date_last_used", models.DateTimeField(null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_accesses",
                        to="tsosi.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityEditLog",
            fields=[
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("changes", models.JSONField()),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_logs",
                        to="tsosi.entityeditaccess",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_logs",
                        to="tsosi.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
