version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    # ports:
    #   - "5173:5173"
    #   - "8000:8000"
    # Bind workspace repository in dev container and Host
    volumes:
      - ../..:/workspaces:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:17
    restart: always
    # TODO: use a bind mount with host folder to access database easily
    # volumes:
    #   - type: bind
    #     source: /tsosi-postgresql
    #     target: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # TODO: put those in an .env file
    environment:
      - POSTGRES_USER=tsosi_user
      - POSTGRES_PASSWORD=tsosi_password
      - POSTGRES_DB=tsosi_db

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
