name: Test Django application

on:
  push:
    branches:
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "backend-test"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  backend-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tsosi-org/backend-test-env:latest
      credentials:
        username: guillaume-uga
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create settings file
        run: cp backend_site/settings_local.example.py backend_site/settings_local.py
      # We would need a way to ignore the log folder in test mode
      - name: Create log folder
        run: mkdir /var/log/tsosi
      # Disable virtualenvs so that poetry uses everything in the main
      # pre-congifureg Python 
      - name: Poetry config
        run: poetry config virtualenvs.create false
      - name: Install missing Python dependecies in case the container is out-of-date
        run: poetry install --no-root
      - name: Run the Python tests
        run: poetry run pytest
        
